---
title: "TSAR Project Assignment Part1"
subtitle: "Exploratory Data Analysis with ggplot2"
author: "Philipp Altenbach, Taoufik Brinis, Ronny Grieder, Ryan Kreis"
date : today
format:
  html:
    theme: zephyr
    code-fold: true
    page-layout: full
#format: pdf #Needs tinytex or similar
editor: visual #Visual editor by default
execute:
  echo: true  # Show code in output by default. If false no code only output.
---

```{r setup, include=FALSE}
# install the required packages if needed
# need to be commented because myLCdata file must not always be created again
# use only myLCdata <- fread("Data/myLCdata.csv")

# if (!require("data.table")) install.packages("data.table") if (!require("dplyr")) install.packages("dplyr") \
# load them 
library(data.table) 
library(dplyr)
library(here)
# 
# LCdata <- fread("Data/LCdata.csv")
# 
# set.seed(5)
# 
# myLCdata <- LCdata %>% sample(5) %>% slice_sample(prop = .5)
# 
# fwrite(myLCdata, file = "Data/myLCdata.csv")
```

```{r include=FALSE}
data_path <- file.path(here(), "Data", "myLCdata.csv")
print(here())
myLCdata <- fread(data_path)
```
